package com.entity;
// Generated 2017-6-4 8:38:49 by Hibernate Tools 3.6.0.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Customer generated by hbm2java
 */
@Entity
@Table(name = "customer", catalog = "supermarket")
public class Customer implements java.io.Serializable {

	private String customerId;
	private String name;
	private String sex;
	private String phone;
	private int code;
	private Set<Dealing> dealings = new HashSet<Dealing>(0);

	public Customer() {
	}

	public Customer(String customerId, String name, String sex, String phone, int code) {
		this.customerId = customerId;
		this.name = name;
		this.sex = sex;
		this.phone = phone;
		this.code = code;
	}

	public Customer(String customerId, String name, String sex, String phone, int code, Set<Dealing> dealings) {
		this.customerId = customerId;
		this.name = name;
		this.sex = sex;
		this.phone = phone;
		this.code = code;
		this.dealings = dealings;
	}

	@Id

	@Column(name = "customerId", unique = true, nullable = false, length = 6)
	public String getCustomerId() {
		return this.customerId;
	}

	public void setCustomerId(String customerId) {
		this.customerId = customerId;
	}

	@Column(name = "name", nullable = false, length = 20)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "sex", nullable = false, length = 4)
	public String getSex() {
		return this.sex;
	}

	public void setSex(String sex) {
		this.sex = sex;
	}

	@Column(name = "phone", nullable = false, length = 20)
	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	@Column(name = "code", nullable = false)
	public int getCode() {
		return this.code;
	}

	public void setCode(int code) {
		this.code = code;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "customer")
	public Set<Dealing> getDealings() {
		return this.dealings;
	}

	public void setDealings(Set<Dealing> dealings) {
		this.dealings = dealings;
	}

}
