package com.entity;
// Generated 2017-6-4 8:38:49 by Hibernate Tools 3.6.0.Final

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Dealing generated by hbm2java
 */
@Entity
@Table(name = "dealing", catalog = "supermarket")
public class Dealing implements java.io.Serializable {

	private Integer id;
	private Customer customer;
	private Admin admin;
	private Good good;
	private int num;
	private Date dealingtime;
	private BigDecimal price;

	public Dealing() {
	}

	public Dealing(Admin admin, Good good, int num, Date dealingtime, BigDecimal price) {
		this.admin = admin;
		this.good = good;
		this.num = num;
		this.dealingtime = dealingtime;
		this.price = price;
	}

	public Dealing(Customer customer, Admin admin, Good good, int num, Date dealingtime, BigDecimal price) {
		this.customer = customer;
		this.admin = admin;
		this.good = good;
		this.num = num;
		this.dealingtime = dealingtime;
		this.price = price;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "customerId")
	public Customer getCustomer() {
		return this.customer;
	}

	public void setCustomer(Customer customer) {
		this.customer = customer;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "adminId", nullable = false)
	public Admin getAdmin() {
		return this.admin;
	}

	public void setAdmin(Admin admin) {
		this.admin = admin;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "goodId", nullable = false)
	public Good getGood() {
		return this.good;
	}

	public void setGood(Good good) {
		this.good = good;
	}

	@Column(name = "num", nullable = false)
	public int getNum() {
		return this.num;
	}

	public void setNum(int num) {
		this.num = num;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dealingtime", nullable = false, length = 19)
	public Date getDealingtime() {
		return this.dealingtime;
	}

	public void setDealingtime(Date dealingtime) {
		this.dealingtime = dealingtime;
	}

	@Column(name = "price", nullable = false, precision = 10)
	public BigDecimal getPrice() {
		return this.price;
	}

	public void setPrice(BigDecimal price) {
		this.price = price;
	}

}
