package com.entity;
// Generated 2017-6-4 8:38:49 by Hibernate Tools 3.6.0.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Goodtype generated by hbm2java
 */
@Entity
@Table(name = "goodtype", catalog = "supermarket")
public class Goodtype implements java.io.Serializable {

	private String goodtypeId;
	private String goodtypeName;
	private Set<Good> goods = new HashSet<Good>(0);

	public Goodtype() {
	}
	
	public Goodtype(String goodtypeId, String goodtypeName) {
		this.goodtypeId = goodtypeId;
		this.goodtypeName = goodtypeName;
	}

	public Goodtype(String goodtypeId, String goodtypeName, Set<Good> goods) {
		this.goodtypeId = goodtypeId;
		this.goodtypeName = goodtypeName;
		this.goods = goods;
	}

	@Id

	@Column(name = "goodtypeId", unique = true, nullable = false, length = 4)
	public String getGoodtypeId() {
		return this.goodtypeId;
	}

	public void setGoodtypeId(String goodtypeId) {
		this.goodtypeId = goodtypeId;
	}

	@Column(name = "goodtypeName", nullable = false, length = 20)
	public String getGoodtypeName() {
		return this.goodtypeName;
	}

	public void setGoodtypeName(String goodtypeName) {
		this.goodtypeName = goodtypeName;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "goodtype")
	public Set<Good> getGoods() {
		return this.goods;
	}

	public void setGoods(Set<Good> goods) {
		this.goods = goods;
	}

}
