package com.entity;
// Generated 2017-6-4 8:38:49 by Hibernate Tools 3.6.0.Final

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Good generated by hbm2java
 */
@Entity
@Table(name = "good", catalog = "supermarket")
public class Good implements java.io.Serializable {

	private String goodId;
	private Goodtype goodtype;
	private String goodName;
	private BigDecimal price;
	private int num;
	private BigDecimal originPrice;
	private Set<Dealing> dealings = new HashSet<Dealing>(0);

	public Good() {
	}

	public Good(String goodId, Goodtype goodtype, String goodName, BigDecimal price, int num, BigDecimal originPrice) {
		this.goodId = goodId;
		this.goodtype = goodtype;
		this.goodName = goodName;
		this.price = price;
		this.num = num;
		this.originPrice = originPrice;
	}

	public Good(String goodId, Goodtype goodtype, String goodName, BigDecimal price, int num, BigDecimal originPrice,
			Set<Dealing> dealings) {
		this.goodId = goodId;
		this.goodtype = goodtype;
		this.goodName = goodName;
		this.price = price;
		this.num = num;
		this.originPrice = originPrice;
		this.dealings = dealings;
	}

	@Id

	@Column(name = "goodId", unique = true, nullable = false, length = 6)
	public String getGoodId() {
		return this.goodId;
	}

	public void setGoodId(String goodId) {
		this.goodId = goodId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "goodtypeId", nullable = false)
	public Goodtype getGoodtype() {
		return this.goodtype;
	}

	public void setGoodtype(Goodtype goodtype) {
		this.goodtype = goodtype;
	}

	@Column(name = "goodName", nullable = false, length = 50)
	public String getGoodName() {
		return this.goodName;
	}

	public void setGoodName(String goodName) {
		this.goodName = goodName;
	}

	@Column(name = "price", nullable = false, precision = 10)
	public BigDecimal getPrice() {
		return this.price;
	}

	public void setPrice(BigDecimal price) {
		this.price = price;
	}

	@Column(name = "num", nullable = false)
	public int getNum() {
		return this.num;
	}

	public void setNum(int num) {
		this.num = num;
	}

	@Column(name = "originPrice", nullable = false, precision = 10)
	public BigDecimal getOriginPrice() {
		return this.originPrice;
	}

	public void setOriginPrice(BigDecimal originPrice) {
		this.originPrice = originPrice;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "good")
	public Set<Dealing> getDealings() {
		return this.dealings;
	}

	public void setDealings(Set<Dealing> dealings) {
		this.dealings = dealings;
	}

}
