package com.entity;
// Generated 2017-6-4 8:38:49 by Hibernate Tools 3.6.0.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Supplier generated by hbm2java
 */
@Entity
@Table(name = "supplier", catalog = "supermarket")
public class Supplier implements java.io.Serializable {

	private String supplierId;
	private String supplierName;
	private String telephone;
	private String email;
	private String address;
	private Set<Inshop> inshops = new HashSet<Inshop>(0);

	public Supplier() {
	}

	public Supplier(String supplierId, String supplierName, String telephone) {
		this.supplierId = supplierId;
		this.supplierName = supplierName;
		this.telephone = telephone;
	}

	public Supplier(String supplierId, String supplierName, String telephone, String email, String address,
			Set<Inshop> inshops) {
		this.supplierId = supplierId;
		this.supplierName = supplierName;
		this.telephone = telephone;
		this.email = email;
		this.address = address;
		this.inshops = inshops;
	}

	@Id

	@Column(name = "supplierId", unique = true, nullable = false, length = 6)
	public String getSupplierId() {
		return this.supplierId;
	}

	public void setSupplierId(String supplierId) {
		this.supplierId = supplierId;
	}

	@Column(name = "supplierName", nullable = false, length = 50)
	public String getSupplierName() {
		return this.supplierName;
	}

	public void setSupplierName(String supplierName) {
		this.supplierName = supplierName;
	}

	@Column(name = "telephone", nullable = false, length = 20)
	public String getTelephone() {
		return this.telephone;
	}

	public void setTelephone(String telephone) {
		this.telephone = telephone;
	}

	@Column(name = "email", length = 30)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "address", length = 80)
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "supplier")
	public Set<Inshop> getInshops() {
		return this.inshops;
	}

	public void setInshops(Set<Inshop> inshops) {
		this.inshops = inshops;
	}

}
