package com.entity;
// Generated 2017-5-23 22:38:04 by Hibernate Tools 3.6.0.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Admin generated by hbm2java
 */
@Entity
@Table(name = "admin", catalog = "market")
public class Admin implements java.io.Serializable {

	private String adminId;
	private String password;
	private String adminName;
	private String sex;
	private String phone;
	private String email;
	private String address;
	private int rankId;
	private Set<Dealing> dealings = new HashSet<Dealing>(0);

	public Admin() {
	}

	public Admin(String adminId, String password, String adminName, String sex, String phone, int rankId) {
		this.adminId = adminId;
		this.password = password;
		this.adminName = adminName;
		this.sex = sex;
		this.phone = phone;
		this.rankId = rankId;
	}

	public Admin(String adminId, String password, String adminName, String sex, String phone, String email,
			String address, int rankId, Set<Dealing> dealings) {
		this.adminId = adminId;
		this.password = password;
		this.adminName = adminName;
		this.sex = sex;
		this.phone = phone;
		this.email = email;
		this.address = address;
		this.rankId = rankId;
		this.dealings = dealings;
	}

	@Id

	@Column(name = "adminId", unique = true, nullable = false, length = 6)
	public String getAdminId() {
		return this.adminId;
	}

	public void setAdminId(String adminId) {
		this.adminId = adminId;
	}

	@Column(name = "password", nullable = false, length = 20)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "adminName", nullable = false, length = 20)
	public String getAdminName() {
		return this.adminName;
	}

	public void setAdminName(String adminName) {
		this.adminName = adminName;
	}

	@Column(name = "sex", nullable = false, length = 4)
	public String getSex() {
		return this.sex;
	}

	public void setSex(String sex) {
		this.sex = sex;
	}

	@Column(name = "phone", nullable = false, length = 20)
	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	@Column(name = "email", length = 30)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "address", length = 80)
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "rankId", nullable = false)
	public int getRankId() {
		return this.rankId;
	}

	public void setRankId(int rankId) {
		this.rankId = rankId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "admin")
	public Set<Dealing> getDealings() {
		return this.dealings;
	}

	public void setDealings(Set<Dealing> dealings) {
		this.dealings = dealings;
	}

}
